### ISSUE TITLE
Remove junit-vintage-engine with the recipe JUnit4to5Migration

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#195]
Given the following dependency : 

```
          <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
```

And recipes : 

```
<recipe>org.openrewrite.java.testing.junit5.JUnit5BestPractices</recipe>
<recipe>org.openrewrite.java.testing.junit5.JUnit4to5Migration </recipe>
```

Rewrite creates the following change : 

```
<dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
         <exclusions>
            <exclusion>
               <groupId>junit</groupId>
               <artifactId>junit</artifactId>
            </exclusion>
         </exclusions>
        </dependency>
```

Where it excludes `junit 4` but still leaves the `junit-vintage-engine` behind

I think that we should remove `junit-vintage-engine` altogether as the only purpose of this package is to be backwards compatible with Junit4 that we are removing with `org.openrewrite.java.testing.junit5.JUnit4to5Migration` 

Additionally, leaving `junit-vintage-engine` in the classpath with JUnit 4 excluded, leads to the following exception at run time : 

```
[ERROR] There was an error in the forked process
[ERROR] TestEngine with ID 'junit-vintage' failed to discover tests
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] TestEngine with ID 'junit-vintage' failed to discover tests
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 

```

See : https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-running

**Comment by pway99** [comment]
Hi @yeikel, This change 0f1417812d272e2499ca33d67480234de0e9436c should have fixed this issue.  
Can you try the latest build and let me know if it's still an issue?

**Comment by yeikel** [comment]
> Hi @yeikel, The recipe should be removing the vintage engine
> 
> https://github.com/openrewrite/rewrite-testing-frameworks/blob/18fb857949e539993fc48785b00a66896d244fad/src/main/resources/META-INF/rewrite/junit5.yml#L90-L92
> 
> Can you try the latest build and let me know if it's still an issue?

Is `org.openrewrite.java.testing.junit5.JUnit5BestPractices` the one I should try?

**Comment by yeikel** [comment]
We should probably consider removing 

``yml


  - org.openrewrite.maven.ExcludeDependency:
      groupId: org.junit.vintage
      artifactId: junit-vintage-engine

```

Adding it as an exclusion is not a "good practice". A good practice is to remove it all together

**Comment by pway99** [comment]
>Is org.openrewrite.java.testing.junit5.JUnit5BestPractices the one I should try?

`Junit5BestPractices` invokes `JUnit4to5Migration` so it should remove the vintage engine dependency
https://github.com/openrewrite/rewrite-testing-frameworks/blob/18fb857949e539993fc48785b00a66896d244fad/src/main/resources/META-INF/rewrite/junit5.yml#L26

>Adding it as an exclusion is not a good practice. A good practice is to remove it all together

Thanks again, I will change that to a `RemoveExclusion`
