### ISSUE TITLE
ParameterizedRunnerToParameterized is flakey when run within JUnit5BestPractices

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-testing-frameworks#230]
I've tried to isolate this as best as I could, but I'm getting some bizarre behaviors, so bear with me. Consider the below test class, which runs `ParameterizedRunnerToParameterized` either by itself or as part of `JUnit5BestPractices` on three different Java SourceFiles.

```kotlin
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import org.openrewrite.java.JavaParser
import org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized
import org.openrewrite.test.RecipeSpec
import org.openrewrite.test.RewriteTest
import java.util.stream.Stream

class MyTest : RewriteTest {
    private companion object {
        private val javaParser = { JavaParser.fromJavaVersion().classpath("junit", "junit-jupiter-params")
            .logCompilationWarningsAndErrors(true).build() }
        @JvmStatic
        fun specConsumers(): Stream<Arguments> = Stream.of(
            Arguments.of(fun(spec: RecipeSpec) {
                spec.recipe(ParameterizedRunnerToParameterized())
                    .parser(javaParser.invoke())
            }),
            Arguments.of(fun(spec: RecipeSpec) {
                spec.recipe(
                    "/META-INF/rewrite/junit5.yml",
                    "org.openrewrite.java.testing.junit5.JUnit5BestPractices"
                )
                    .parser(javaParser.invoke())
            }),
//            Arguments.of(fun(spec: RecipeSpec) {
//                spec.recipe(ParameterizedRunnerToParameterized())
//                    .parser(javaParser.invoke())
//            }),
        )
    }

    @ParameterizedTest
    @MethodSource("specConsumers")
    fun beforeTest(spec: (RecipeSpec) -> Unit) = rewriteRun(spec, java("""
        import org.junit.Assert;
        import org.junit.Assume;
        import org.junit.Test;
        import org.junit.runner.RunWith;
        import org.junit.runners.Parameterized;
        import org.junit.runners.Parameterized.BeforeParam;
        import org.junit.runners.Parameterized.Parameters;
        
        import java.util.Arrays;
        
        @RunWith(Parameterized.class)
        public class BeforeTest {
            @Parameters
            public static Iterable<String> data() {
                return Arrays.asList("first test", "second input");
            }
        
            private final String input;
        
            public BeforeTest(final String input) {
                this.input = input;
            }
        
            @BeforeParam
            public static void ensureParamSaysTest(String input) {
                Assume.assumeTrue(input.contains("test"));
            }
        
            @Test
            public void test() {
                Assert.assertTrue(input.contains("first"));
            }
        }
    """.trimIndent(), """
        import org.junit.Assert;
        import org.junit.Assume;
        import org.junit.jupiter.params.ParameterizedTest;
        import org.junit.jupiter.params.provider.MethodSource;
        import org.junit.runners.Parameterized.BeforeParam;
        
        import java.util.Arrays;
        
        public class BeforeTest {
            public static Iterable<String> data() {
                return Arrays.asList("first test", "second input");
            }
        
            private String input;
        
            public void initBeforeTest(final String input) {
                this.input = input;
            }
        
            @BeforeParam
            public static void ensureParamSaysTest(String input) {
                Assume.assumeTrue(input.contains("test"));
            }
        
            @MethodSource("data")
            @ParameterizedTest
            public void test(final String input) {
                this.initBeforeTest(input);
                Assert.assertTrue(input.contains("first"));
            }
        }
    """.trimIndent()))

    @ParameterizedTest
    @MethodSource("specConsumers")
    fun constructorInjectionTest(spec: (RecipeSpec) -> Unit) = rewriteRun(spec, java("""
        import org.junit.Test;
        import org.junit.runner.RunWith;
        import org.junit.runners.Parameterized;
        
        import java.util.Arrays;
        
        import static org.junit.Assert.assertEquals;
        import static org.junit.runners.Parameterized.*;
        
        @RunWith(Parameterized.class)
        public class ConstructorInjectionTest {
        
            @Parameters(name = "{index}: {0} + {1} = {2}")
            public static Iterable<Object[]> data() {
                return Arrays.asList(new Object[][] { { 0, 0, 0 }, { 1, 1, 2 },
                        { 3, 2, 5 }, { 4, 3, 7 } });
            }
        
            private final int firstSummand;
            private final int secondSummand;
            private final int sum;
        
            public ConstructorInjectionTest(int firstSummand, int secondSummand, int sum) {
                this.firstSummand = firstSummand;
                this.secondSummand = secondSummand;
                this.sum = sum;
            }
        
            @Test
            public void test() {
                assertEquals(sum, firstSummand + secondSummand);
            }
        }
    """.trimIndent(), """
        import org.junit.jupiter.params.ParameterizedTest;
        import org.junit.jupiter.params.provider.MethodSource;
        
        import java.util.Arrays;
        
        import static org.junit.Assert.assertEquals;
        
        public class ConstructorInjectionTest {
        
            public static Iterable<Object[]> data() {
                return Arrays.asList(new Object[][]{{0, 0, 0}, {1, 1, 2},
                        {3, 2, 5}, {4, 3, 7}});
            }
        
            private int firstSummand;
            private int secondSummand;
            private int sum;
        
            public void initConstructorInjectionTest(int firstSummand, int secondSummand, int sum) {
                this.firstSummand = firstSummand;
                this.secondSummand = secondSummand;
                this.sum = sum;
            }
        
            @MethodSource("data")
            @ParameterizedTest(name = "{index}: {0} + {1} = {2}")
            public void test(int firstSummand, int secondSummand, int sum) {
                this.initConstructorInjectionTest(firstSummand, secondSummand, sum);
                assertEquals(sum, firstSummand + secondSummand);
            }
        }
    """.trimIndent()))

    @ParameterizedTest
    @MethodSource("specConsumers")
    fun fieldInjectionTest(spec: (RecipeSpec) -> Unit) = rewriteRun(spec, java("""
        import org.junit.Test;
        import org.junit.runner.RunWith;
        import org.junit.runners.Parameterized;
        
        import java.util.Arrays;
        
        import static org.junit.Assert.assertEquals;
        import static org.junit.runners.Parameterized.*;
        
        @RunWith(Parameterized.class)
        public class FieldInjectionTest {
            @Parameters(name = "{index}: {0} + {1} = {2}")
            public static Iterable<Object[]> data() {
                return Arrays.asList(new Object[][] { { 0, 0, 0 }, { 1, 1, 2 }, { 3, 2, 5 }, { 4, 3, 7 } });
            }
        
            @Parameter(0)
            public int firstSummand;
        
            @Parameter(1)
            public int secondSummand;
        
            @Parameter(2)
            public int sum;
        
            @Test
            public void test() {
                assertEquals(sum, firstSummand + secondSummand);
            }
        }
    """.trimIndent(), """
        import org.junit.jupiter.params.ParameterizedTest;
        import org.junit.jupiter.params.provider.MethodSource;
        
        import java.util.Arrays;
        
        import static org.junit.Assert.assertEquals;
        
        public class FieldInjectionTest {
            public static Iterable<Object[]> data() {
                return Arrays.asList(new Object[][]{{0, 0, 0}, {1, 1, 2}, {3, 2, 5}, {4, 3, 7}});
            }
            public int firstSummand;
            public int secondSummand;
            public int sum;
        
            @MethodSource("data")
            @ParameterizedTest(name = "{index}: {0} + {1} = {2}")
            public void test(int firstSummand, int secondSummand, int sum) {
                this.initFieldInjectionTest(firstSummand, secondSummand, sum);
                assertEquals(sum, firstSummand + secondSummand);
            }
        
            public void initFieldInjectionTest(int firstSummand, int secondSummand, int sum) {
                this.firstSummand = firstSummand;
                this.secondSummand = secondSummand;
                this.sum = sum;
            }
        }
    """.trimIndent()))
}
```

First thing to note: in each test case, I've qualified the call to `init{ClassName}` with `this.` in the expected Java String, even though this doesn't actually match recipe output. I did this because without the qualifier, the test scaffold throws an exception, such as this:
```
java.lang.IllegalStateException: AST contains missing or invalid type information
MethodInvocation->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
/*~~(MethodInvocation type is null)~~>*/initBeforeTest(input)
	at org.openrewrite.java.TypeValidation.assertValidTypes(TypeValidation.java:63)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:358)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:87)
	at MyTest.beforeTest(MyTest.kt:36)
```
So, for the rest of this issue, whenever I refer to a "successful" test case, I actually mean a failure where the only difference is the addition of the `this.` qualifier.

On my machine, the test class gives these results:
* Constructor Injection Test:
  * ParameterizedRunnerToParameterized: success
  * JUnit5BestPractices: success (ignoring that it also adds some other JUnit5 changes)
* Field Injection Test: 
  * ParameterizedRunnerToParameterized: success
  * JUnit5BestPractices: **_Stack trace [A] below_**
* Before Test:
  * ParameterizedRunnerToParameterized: success
  * JUnit5BestPractices: success (ignoring that it also adds some other JUnit5 changes)

One scenario fails in an odd way.

Getting weirder: if I flip around the elements of the Arguments Stream to run the recipe test cases in the opposite order, then I get considerably different results, and *most* of the cases fail:
* Constructor Injection Test:
  * JUnit5BestPractices: Stack trace [B] below
  * ParameterizedRunnerToParameterized: Stack trace [B] below
* Field Injection Test: 
  * JUnit5BestPractices: Stack trace [B] below
  * ParameterizedRunnerToParameterized: Stack trace [B] below
* Before Test:
  * JUnit5BestPractices: `org.opentest4j.AssertionFailedError: [Expected recipe to complete in 1 cycle, but took at least one more cycle. Between the last two executed cycles there were changes.] `, with the diff showing changes with whether the `assertTrue` import is static
  * ParameterizedRunnerToParameterized: success

I saw that `JavaTemplate` has some caching logic, so maybe that explains how order of execution seems to affect independent test cases... but I'm still stumped on root cause. It seems like there might be a few issues going on here.

Stack Trace [A]
```
java.lang.AssertionError: Failed to run parse sources or recipe
[...]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.openrewrite.java.internal.template.JavaTemplateParser.compileTemplate(JavaTemplateParser.java:247)
	at org.openrewrite.java.internal.template.JavaTemplateParser.parseBlockStatements(JavaTemplateParser.java:166)
	at org.openrewrite.java.JavaTemplate$2.visitBlock(JavaTemplate.java:124)
	at org.openrewrite.java.JavaTemplate$2.visitBlock(JavaTemplate.java:103)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:720)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:154)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:513)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:43)
	at org.openrewrite.java.tree.J.withTemplate(J.java:80)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitClassDeclaration(ParameterizedRunnerToParameterized.java:262)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitClassDeclaration(ParameterizedRunnerToParameterized.java:152)
	at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:992)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:287)
	at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:471)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
	at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:471)
	at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:119)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitCompilationUnit(ParameterizedRunnerToParameterized.java:235)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitCompilationUnit(ParameterizedRunnerToParameterized.java:152)
	at org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:459)
	at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:39)
	at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1226)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$5(RecipeScheduler.java:245)
[...]
```

Stack Trace [B]
```
java.lang.AssertionError: Failed to run parse sources or recipe
[...]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.openrewrite.java.JavaTemplate$2.visitAnnotation(JavaTemplate.java:109)
	at org.openrewrite.java.JavaTemplate$2.visitAnnotation(JavaTemplate.java:103)
	at org.openrewrite.java.tree.J$Annotation.acceptJava(J.java:208)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:154)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:513)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:43)
	at org.openrewrite.java.tree.J.withTemplate(J.java:80)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.lambda$visitMethodDeclaration$8(ParameterizedRunnerToParameterized.java:328)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitMethodDeclaration(ParameterizedRunnerToParameterized.java:321)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitMethodDeclaration(ParameterizedRunnerToParameterized.java:152)
	at org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3042)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:287)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1233)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:372)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:371)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:94)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:720)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:287)
	at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:452)
	at org.openrewrite.java.JavaIsoVisitor.visitClassDeclaration(JavaIsoVisitor.java:114)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitClassDeclaration(ParameterizedRunnerToParameterized.java:255)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitClassDeclaration(ParameterizedRunnerToParameterized.java:152)
	at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:992)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:287)
	at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:471)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
	at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:471)
	at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:119)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitCompilationUnit(ParameterizedRunnerToParameterized.java:235)
	at org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized$ParameterizedRunnerToParameterizedTestsVisitor.visitCompilationUnit(ParameterizedRunnerToParameterized.java:152)
	at org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:459)
	at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:39)
	at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1226)
	at org.openrewrite.java.tree.J.accept(J.java:53)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:213)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$5(RecipeScheduler.java:245)
[...]
```

Thoughts?

**Comment by pway99** [comment]
Thanks for the detailed issue @nmck257!  We'll have a look
