### ISSUE TITLE
Avoid using AssertJ's withFailMessage since it loses expected and actual values

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-testing-frameworks#234]
See https://github.com/openrewrite/rewrite-testing-frameworks/blob/efc83cc608045b7e747bcd6a793b535e5ac4e540/src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertTrueToAssertThat.java#L89

For instance:

```java
assertThat("hello").withFailMessage(() -> "fail message").isEqualTo("world");
```

would fail as following (note that expected and actual values are missing)

```
java.lang.AssertionError: fail message
	at org.assertj.core.error.AssertionErrorCreator.assertionError(AssertionErrorCreator.java:93)
	at org.assertj.core.internal.Failures.failure(Failures.java:166)
	at org.assertj.core.internal.Failures.failureIfErrorMessageIsOverridden(Failures.java:152)
	at org.assertj.core.internal.Failures.failure(Failures.java:102)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:339)
	at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:362)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:403)
```

A much better alternative would be 

```java
assertThat("hello").as(() -> "fail message").isEqualTo("world");
```

which yields

```
org.opentest4j.AssertionFailedError: [fail message] 
expected: "world"
 but was: "hello"
Expected :"world"
Actual   :"hello"
<Click to see difference>

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.assertj.core.error.ConstructorInvoker.newInstance(ConstructorInvoker.java:28)
	at org.assertj.core.error.ShouldBeEqual.assertionFailedError(ShouldBeEqual.java:223)
	at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:122)
	at org.assertj.core.internal.Failures.failure(Failures.java:105)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:339)
	at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:362)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:403)
```

**Comment by tkvangorder** [comment]
Thanks for the reminder, at the time we originally had written this recipe, there was no method signature that took a supplier. 

https://github.com/assertj/assertj-core/issues/2061
