### ISSUE TITLE
CI Build for `rewrite-testing-frameworks` fails when constructing the `Java11Parser`

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-testing-frameworks#245]
The CI build is flaky and fails quite often when constructing the Java11Parser.

- This error DOES NOT surface when running the tests locally.
- This error occurs when constructing a Java Parser that loads dependencies stubs from a classpath resource.
 
The most obvious use cases where this occurs are the recipes that are using the  AssertJ stubs, but I have also seen this error from `ParameterizedRunnerToParameterized`

See the following stack trace as an example:

Things I have tried: 

- Corrected compiler errors in the AssertJ stubs.
- Created a test harness and loaded the stubs in multiple threads, I was not able to reproduce this.
- Swapped out the java distribution (from Temurin to Zulu), and the error continues to manifest.

```
java.lang.AssertionError: Failed to run parse sources or recipe
	at org.openrewrite.RecipeTest$DefaultImpls._get_executionContext_$lambda-0(RecipeTest.kt:36)
	at org.openrewrite.RecipeTest$DefaultImpls$$Lambda$442/0x000000080122fa90.accept(Unknown Source)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$5(RecipeScheduler.java:244)
	at org.openrewrite.RecipeScheduler$$Lambda$578/0x0000000801344d00.apply(Unknown Source)
	at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:49)
	at org.openrewrite.RecipeScheduler$$Lambda$579/0x0000000801344f70.call(Unknown Source)
	at org.openrewrite.scheduling.DirectScheduler.schedule(DirectScheduler.java:35)
	at org.openrewrite.RecipeScheduler.mapAsync(RecipeScheduler.java:50)
	at org.openrewrite.RecipeScheduler.scheduleVisit(RecipeScheduler.java:190)
	at org.openrewrite.RecipeTest$RecipeSchedulerCheckingExpectedCycles.scheduleVisit(RecipeTest.kt:218)
	at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:86)
	at org.openrewrite.Recipe.run(Recipe.java:287)
	at org.openrewrite.RecipeTest$DefaultImpls.assertChangedBase(RecipeTest.kt:108)
	at org.openrewrite.RecipeTest$DefaultImpls.assertChangedBase(RecipeTest.kt:57)
	at org.openrewrite.java.JavaRecipeTest$DefaultImpls.assertChanged(JavaRecipeTest.kt:66)
	at org.openrewrite.java.testing.assertj.JUnitAssertSameToAssertThatTest.assertChanged(JUnitAssertSameToAssertThatTest.kt:23)
	at org.openrewrite.java.JavaRecipeTest$DefaultImpls.assertChanged$default(JavaRecipeTest.kt:49)
	at org.openrewrite.java.testing.assertj.JUnitAssertSameToAssertThatTest.singleStaticMethodWithMessageSupplier(JUnitAssertSameToAssertThatTest.kt:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$188/0x000000080111fcc8.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall$$Lambda$189/0x000000080111a208.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$$Lambda$341/0x00000008011479f0.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$429/0x0000000801214fe0.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$272/0x0000000801139a80.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$271/0x0000000801139850.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$270/0x0000000801139418.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$276/0x000000080113a5c0.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$272/0x0000000801139a80.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$271/0x0000000801139850.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$270/0x0000000801139418.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$276/0x000000080113a5c0.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$272/0x0000000801139a80.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$271/0x0000000801139850.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$270/0x0000000801139418.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda$232/0x0000000801127408.accept(Unknown Source)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.openrewrite.UncaughtVisitorException: java.lang.IllegalStateException: Unable to construct Java11Parser.
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:253)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:145)
	at app//org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:520)
	at app//org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:42)
	at app//org.openrewrite.java.tree.J.withTemplate(J.java:82)
	at app//org.openrewrite.java.testing.assertj.JUnitAssertSameToAssertThat$AssertSameToAssertThatVisitor.visitMethodInvocation(JUnitAssertSameToAssertThat.java:94)
	at app//org.openrewrite.java.testing.assertj.JUnitAssertSameToAssertThat$AssertSameToAssertThatVisitor.visitMethodInvocation(JUnitAssertSameToAssertThat.java:62)
	at app//org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3409)
	at app//org.openrewrite.java.tree.J.accept(J.java:55)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at app//org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1231)
	at app//org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:373)
	at app//org.openrewrite.java.JavaVisitor$$Lambda$584/0x000000080134c8f8.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
	at app//org.openrewrite.internal.ListUtils$$Lambda$568/0x0000000801289400.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
	at app//org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:372)
	at app//org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:94)
	at app//org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:31)
	at app//org.openrewrite.java.tree.J$Block.acceptJava(J.java:740)
	at app//org.openrewrite.java.tree.J.accept(J.java:55)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at app//org.openrewrite.java.JavaVisitor.visitMethodDeclaration(JavaVisitor.java:815)
	at app//org.openrewrite.java.JavaIsoVisitor.visitMethodDeclaration(JavaIsoVisitor.java:225)
	at app//org.openrewrite.java.JavaIsoVisitor.visitMethodDeclaration(JavaIsoVisitor.java:31)
	at app//org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3156)
	at app//org.openrewrite.java.tree.J.accept(J.java:55)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at app//org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1231)
	at app//org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:373)
	at app//org.openrewrite.java.JavaVisitor$$Lambda$584/0x000000080134c8f8.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
	at app//org.openrewrite.internal.ListUtils$$Lambda$568/0x0000000801289400.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
	at app//org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:372)
	at app//org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:94)
	at app//org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:31)
	at app//org.openrewrite.java.tree.J$Block.acceptJava(J.java:740)
	at app//org.openrewrite.java.tree.J.accept(J.java:55)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at app//org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:453)
	at app//org.openrewrite.java.JavaIsoVisitor.visitClassDeclaration(JavaIsoVisitor.java:114)
	at app//org.openrewrite.java.JavaIsoVisitor.visitClassDeclaration(JavaIsoVisitor.java:31)
	at app//org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1064)
	at app//org.openrewrite.java.tree.J.accept(J.java:55)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at app//org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:472)
	at app//org.openrewrite.java.JavaVisitor$$Lambda$583/0x000000080134c200.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
	at app//org.openrewrite.internal.ListUtils$$Lambda$568/0x0000000801289400.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
	at app//org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:472)
	at app//org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:119)
	at app//org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:31)
	at app//org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:460)
	at app//org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:39)
	at app//org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:31)
	at app//org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1299)
	at app//org.openrewrite.java.tree.J.accept(J.java:55)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at app//org.openrewrite.RecipeScheduler.lambda$scheduleVisit$5(RecipeScheduler.java:234)
	... 114 more
Caused by: java.lang.IllegalStateException: Unable to construct Java11Parser.
	at org.openrewrite.java.Java11Parser$Builder.build(Java11Parser.java:109)
	at org.openrewrite.java.Java11Parser$Builder.build(Java11Parser.java:75)
	at org.openrewrite.java.testing.assertj.JUnitAssertSameToAssertThat$AssertSameToAssertThatVisitor.lambda$new$0(JUnitAssertSameToAssertThat.java:64)
	at org.openrewrite.java.testing.assertj.JUnitAssertSameToAssertThat$AssertSameToAssertThatVisitor$$Lambda$786/0x0000000801404a10.get(Unknown Source)
	at org.openrewrite.java.internal.template.JavaTemplateParser.compileTemplate(JavaTemplateParser.java:247)
	at org.openrewrite.java.internal.template.JavaTemplateParser.parseBlockStatements(JavaTemplateParser.java:166)
	at org.openrewrite.java.JavaTemplate$2.maybeReplaceStatement(JavaTemplate.java:482)
	at org.openrewrite.java.JavaTemplate$2.visitMethodInvocation(JavaTemplate.java:462)
	at org.openrewrite.java.JavaTemplate$2.visitMethodInvocation(JavaTemplate.java:102)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3409)
	at org.openrewrite.java.tree.J.accept(J.java:55)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	... 182 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openrewrite.java.Java11Parser$Builder.build(Java11Parser.java:105)
	... 193 more
Caused by: java.lang.IllegalStateException: Call reset() on JavaParser before parsing anotherset of source files that have some of the same fully qualified names
	at org.openrewrite.java.isolated.ReloadableJava11Parser.lambda$parseInputsToCompilerAst$2(ReloadableJava11Parser.java:244)
	at org.openrewrite.java.isolated.ReloadableJava11Parser$$Lambda$453/0x000000080120ca68.get(Unknown Source)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:65)
	at org.openrewrite.java.isolated.ReloadableJava11Parser.parseInputsToCompilerAst(ReloadableJava11Parser.java:239)
	at org.openrewrite.java.isolated.ReloadableJava11Parser.parseInputs(ReloadableJava11Parser.java:160)
	at org.openrewrite.java.isolated.ReloadableJava11Parser.compileDependencies(ReloadableJava11Parser.java:312)
	at org.openrewrite.java.isolated.ReloadableJava11Parser.<init>(ReloadableJava11Parser.java:150)
	... 198 more
Caused by: java.lang.IllegalStateException: endPosTable already set
	at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
	at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:413)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:659)
	at org.openrewrite.java.isolated.ReloadableJava11Parser.lambda$parseInputsToCompilerAst$2(ReloadableJava11Parser.java:241)
	... 204 more
```

**Comment by tkvangorder** [comment]
This was fixed as part of #2167
