### ISSUE TITLE
Unable to find runtime dependencies beginning with: 'junit-jupiter-api' in `RunnerToExtension`

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#306]
**Steps to reproduce**

1. `git clone https://github.com/spring-projects/spring-petclinic.git`
2. `git checkout 1.5.x`
3. `./mvnw wrapper:wrapper -Dmaven=3.8.7` (optional)
4. `./mvnw -B -U -X org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:LATEST -DactiveRecipes=org.openrewrite.java.spring.boot2.SpringBoot1To2Migration`

**Expected**
Application migrated to use JUnit 5, among other changes.

**Actual**

Stacktrace in `RunnerToExtension` related to `junit-jupiter-api`.
```java
Caused by: org.openrewrite.internal.RecipeRunException: Exception while visiting project file 'src/test/java/org/springframework/samples/petclinic/vet/VetControllerTests.java (in VetControllerTests)', caused by: java.lang.IllegalArgumentException: Unable to find runtime dependencies beginning with: 'junit-jupiter-api', at org.openrewrite.java.JavaParser.dependenciesFromClasspath(JavaParser.java:101)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:324)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.lambda$visitClassDeclaration$5(JavaVisitor.java:421)
...
Caused by: java.lang.IllegalArgumentException: Unable to find runtime dependencies beginning with: 'junit-jupiter-api'
	at org.openrewrite.java.JavaParser.dependenciesFromClasspath(JavaParser.java:101)
	at org.openrewrite.java.JavaParser$Builder.classpath(JavaParser.java:254)
	at org.openrewrite.java.testing.junit5.RunnerToExtension$2.lambda$getExtendsWithTemplate$0(RunnerToExtension.java:95)
	at org.openrewrite.java.internal.template.JavaTemplateParser.compileTemplate(JavaTemplateParser.java:247)
	at org.openrewrite.java.internal.template.JavaTemplateParser.lambda$parseAnnotations$7(JavaTemplateParser.java:207)
	at org.openrewrite.java.internal.template.JavaTemplateParser.cache(JavaTemplateParser.java:256)
	at org.openrewrite.java.internal.template.JavaTemplateParser.parseAnnotations(JavaTemplateParser.java:204)
	at org.openrewrite.java.JavaTemplate$2.visitAnnotation(JavaTemplate.java:117)
	at org.openrewrite.java.JavaTemplate$2.visitAnnotation(JavaTemplate.java:112)
	at org.openrewrite.java.tree.J$Annotation.acceptJava(J.java:221)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	... 42 more
```

There have been some changes here when [comparing 1.33.0](https://github.com/openrewrite/rewrite-testing-frameworks/blob/v1.33.0/src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java#L94) with [current](https://github.com/openrewrite/rewrite-testing-frameworks/blob/401d7f946e079faa11dd03c527ea63101a903689/src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java#L95) that introduce `classpathFromResources`.

**Comment by timtebeek** [comment]
Hopefully fixed with https://github.com/openrewrite/rewrite-testing-frameworks/commit/998c012881d90ec37958bfa6821165892dbe4d67
